DROP DATABASE IF EXISTS yarnshop;
DROP USER  `ysadmin`@`%`;
DROP USER `ysuser`@`%`;
CREATE DATABASE  yarnshop CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER  `ysadmin`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `yarnshop`.* TO `ysadmin`@`%`;
CREATE USER  `ysuser`@`%` IDENTIFIED  BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `yarnshop`.* TO `ysuser`@`%`;
FLUSH PRIVILEGES;
